python manage.py Import_Stock_Industry --stocksymbol="data\TW.txt" 
python manage.py Import_Stock_Industry --stocksymbol="data\FS.txt"
python manage.py Import_Stock_Industry --stocksymbol="data\FX.txt" 
python manage.py Import_Stock_Industry --stocksymbol="data\HK.txt"
python manage.py Import_Stock_Industry --stocksymbol="data\JP.txt"
python manage.py Import_Stock_Industry --stocksymbol="data\KS.txt"
python manage.py Import_Stock_Industry --stocksymbol="data\SI.txt" 
python manage.py Import_Stock_Industry --stocksymbol="data\US.txt"
python manage.py Import_Stock_Industry --stocksymbol="data\WS.txt"
python manage.py Import_Stock_Industry --stockindustry="data\stockindustry.txt" 
python manage.py Import_Stock_Industry --stockindustryratio="data\stockindustryratio.txt" 
python manage.py Import_Stock_Industry --stockconceptgroup="data\stockconceptgroup.txt"
python manage.py Import_Stock_Industry --stockconceptgrouprelation="data\stockconceptgrouprelation.txt"

python manage.py Import_DJStock --closefile="data\US_All.txt" --market="US"
python manage.py Import_DJStock --closefile="data\USD_Update.txt" --market="US"
python manage.py Import_DJStock --closefile="data\USW_Update.txt" --market="US"

python manage.py Import_DJStock --closefile="data\HK_All.txt" --market="HK"
python manage.py Import_DJStock --closefile="data\HKD_Update.txt" --market="HK"
python manage.py Import_DJStock --closefile="data\HKW_Update.txt" --market="HK"